- name: Patch remote server
  hosts: aws_servers
  become_user: root
  become: yes
  tasks:
    - name: Copy a file to remote server
      dnf:
        name: "bash-completion"
        state: latest
        disablerepo: kubernetes