- name: Patch remote server
  hosts: appserver
  become_user: root
  become: yes
  tasks:
    - name: Take prechecks
      copy:
        src: /etc/{{item}}
        dest: /tmp/{{item}}_bkp
        remote_src: yes
      with_items:
        - fstab
        - resolv.conf
    - name: Patch the server
      dnf:
        name: "*"
        state: latest
        disablerepo: kubernetes
    - name: find out whether reboot needed or not
      become: true
      shell: needs-restarting -r
      register: result
      ignore_errors: yes
      failed_when: true
      changed_when: result.rc != 0
      notify:
        - Reboot server
  handlers:
    - name: Reboot server
      become: true
      reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 300
        test_command: whoami