- name: Patch remote server
  hosts: appserver
  tasks:
    - name: Copy a file to remote server
      dnf:
        name: "*"
        state: latest
        disablerepo: kubernetes
        become: yes
        become_user: root
 