- name: Patch remote server
  hosts: appserver
  become_user: root
  become: yes
  tasks:
    - name: Take prechecks
      copy:
        src: /etc/{{item}}
        dest: /tmp/{{item}}_bkp
        remote_src: yes
      with_items:
        - fstab
        - resolv.conf
    - name: Patch the server
      dnf:
        name: "*"
        state: latest
        disablerepo: kubernetes
    - name: find out whether reboot needed or not
      shell: needs-restarting -r >/dev/null
      register: result
      ignore_errors: yes
    - name: Reboot the system if it is needed
      reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 600
        become: true
        async: 30
        poll: 0
        test_command: whoami
      when: result.rc == 0
    - name: Pausing to allow server to shutdown and terminate our SSH connection
      pause: 
        seconds: 30
      when: result.rc == 0
